export const jobs = [
  {
    id: "JHR-2024-001",
    title: "Senior Full Stack Developer",
    department: "Engineering",
    location: "San Francisco, CA",
    postedDate: "2024-01-15",
    totalApplicants: 45,
    matchRate: 18,
    matchSummary: {
      strong: 8,
      potential: 15,
      irrelevant: 22,
    },
  },
  {
    id: "JHR-2024-002",
    title: "Product Manager",
    department: "Product",
    location: "New York, NY",
    postedDate: "2024-01-12",
    totalApplicants: 32,
    matchRate: 16,
    matchSummary: {
      strong: 5,
      potential: 12,
      irrelevant: 15,
    },
  },
  {
    id: "JHR-2024-003",
    title: "UX Designer",
    department: "Design",
    location: "Remote",
    postedDate: "2024-01-10",
    totalApplicants: 28,
    matchRate: 21,
    matchSummary: {
      strong: 6,
      potential: 10,
      irrelevant: 12,
    },
  },
  {
    id: "JHR-2024-004",
    title: "DevOps Engineer",
    department: "Engineering",
    location: "Austin, TX",
    postedDate: "2024-01-08",
    totalApplicants: 18,
    matchRate: 17,
    matchSummary: {
      strong: 3,
      potential: 8,
      irrelevant: 7,
    },
  },
];

export const applicants = {
  "JHR-2024-001": [
    {
      name: "Ali Khan",
      email: "ali.khan@email.com",
      location: "Karachi, Pakistan",
      experience: "5+ years",
      skills: ["React", "TypeScript", "Node.js", "AWS"],
      score: 92,
      classification: "Strong Match",
      appliedDate: "2024-01-15",
    },
    {
      name: "Fatima Noor",
      email: "fatima.noor@email.com",
      location: "Karachi, Pakistan",
      experience: "4 years",
      skills: ["React", "Node.js", "PostgreSQL", "Docker"],
      score: 85,
      classification: "Strong Match",
      appliedDate: "2024-01-12",
    },
    {
      name: "Usman Ahmed",
      email: "usman.ahmed@email.com",
      location: "Karachi, Pakistan",
      experience: "3 years",
      skills: ["JavaScript", "React", "Python"],
      score: 78,
      classification: "Potential Match",
      appliedDate: "2024-01-14",
    },
    {
      name: "Hira Siddiqui",
      email: "hira.siddiqui@email.com",
      location: "Karachi, Pakistan",
      experience: "2 years",
      skills: ["JavaScript", "Vue.js", "MySQL"],
      score: 67,
      classification: "Potential Match",
      appliedDate: "2024-01-11",
    },
  ],
  "JHR-2024-002": [],
  "JHR-2024-003": [],
  "JHR-2024-004": [],
};

export const shortlistedCandidates = [
  {
    name: "Fahad Ahmed Khan",
    jobMatched: "Yes",
    experience: "4 years",
    matchedScore: 100,
    status: "Active",
  },
  {
    name: "Syed Ebad",
    jobMatched: "Yes",
    experience: "14 years",
    matchedScore: 100,
    status: "Active",
  },
  {
    name: "Abdullah Hussain",
    jobMatched: "Yes",
    experience: "4 years",
    matchedScore: 90,
    status: "Active",
  },
  {
    name: "AMBREEN ABIDI",
    jobMatched: "Yes",
    experience: "4 years",
    matchedScore: 80,
    status: "Active",
  },
  {
    name: "OMAIR HANIF KHIMANI",
    jobMatched: "Yes",
    experience: "5 years",
    matchedScore: 100,
    status: "Active",
  },
  {
    name: "AFSHAN NOOR",
    jobMatched: "Yes",
    experience: "0.8 years",
    matchedScore: 60,
    status: "Inactive",
  },
];
